/* Animal Rider - offline service worker (Microsoft Store / GitHub Pages PWA build)
 *
 * GENERATED by store/build_pwa.py - DO NOT HAND-EDIT.
 * Any manual change is destroyed on the next build. Edit build_pwa.py instead.
 *
 * Versioning
 *   CACHE below is a SHA-256 of every deployed file's path and bytes, so the
 *   version bumps itself whenever the content changes and never when it does
 *   not. `activate` then deletes every cache that is not this one. There is no
 *   "remember to bump the version" step to forget.
 *
 * Caching, in two stages
 *   install   SHELL only (19 files, 1.25 MB) - HTML, JS, small icons.
 *             addAll is atomic, so this set is kept small and fast on purpose.
 *   activate  the zone artwork (33 files, 16.61 MB) is then fetched in
 *             the BACKGROUND, one request at a time, each failure isolated. A
 *             flaky first load degrades to "that zone fetches later", never to
 *             "install failed, no offline at all".
 *
 * Request strategy
 *   navigation : network-first, cache fallback
 *       -> an online player always gets the freshest build, so a redeploy can
 *          never be masked by a stale cached page; offline still gets the last
 *          good copy.
 *   everything else : cache-first
 *       -> Vite asset filenames are content-hashed and the artwork is
 *          immutable per CACHE version, so a hit is always the correct bytes.
 *
 * sw.js itself is never precached - a service worker must not cache itself.
 */
const CACHE = 'animal-rider-v1-ff68680c';

/* Precached during install - atomic, keep it small. */
const SHELL = [
  './',
  './.nojekyll',
  './README.md',
  './assets/index-BCqi9kSB.js',
  './icons/icon-128.png',
  './icons/icon-144.png',
  './icons/icon-152.png',
  './icons/icon-192.png',
  './icons/icon-256.png',
  './icons/icon-384.png',
  './icons/icon-48.png',
  './icons/icon-512.png',
  './icons/icon-72.png',
  './icons/icon-96.png',
  './icons/maskable-192.png',
  './icons/maskable-512.png',
  './index.html',
  './manifest.json',
  './privacy.html'
];

/* Warmed in the background after activate - individually, failure-tolerant. */
const DEFERRED = [
  './icons/icon-1024.png',
  './icons/icon-600.png',
  './icons/maskable-1024.png',
  './zones/desert/L1_sky.png',
  './zones/desert/L2_far.png',
  './zones/desert/L3_mid.png',
  './zones/desert/L4_near.png',
  './zones/desert/ground_tile.png',
  './zones/forest/L1_sky.png',
  './zones/forest/L2_far.png',
  './zones/forest/L3_mid.png',
  './zones/forest/L4_near.png',
  './zones/forest/ground_tile.png',
  './zones/meadow/L1_sky.png',
  './zones/meadow/L2_far.png',
  './zones/meadow/L3_mid.png',
  './zones/meadow/L4_near.png',
  './zones/meadow/ground_tile.png',
  './zones/snow/L1_sky.png',
  './zones/snow/L2_far.png',
  './zones/snow/L3_mid.png',
  './zones/snow/L4_near.png',
  './zones/snow/ground_tile.png',
  './zones/starry/L1_sky.png',
  './zones/starry/L2_far.png',
  './zones/starry/L3_mid.png',
  './zones/starry/L4_near.png',
  './zones/starry/ground_tile.png',
  './zones/volcano/L1_sky.png',
  './zones/volcano/L2_far.png',
  './zones/volcano/L3_mid.png',
  './zones/volcano/L4_near.png',
  './zones/volcano/ground_tile.png'
];

self.addEventListener('install', e => {
  e.waitUntil(
    caches.open(CACHE)
      .then(c => c.addAll(SHELL))
      .then(() => self.skipWaiting())
      .catch(() => self.skipWaiting())
  );
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
      .then(() => caches.open(CACHE).then(warm))
  );
});

/* Sequential on purpose: parallel warming of the artwork would compete with
 * the very first frames of the game for bandwidth. */
function warm(cache) {
  return DEFERRED.reduce(
    (chain, url) => chain.then(() =>
      cache.match(url).then(hit => hit ? undefined : cache.add(url).catch(() => {}))
    ),
    Promise.resolve()
  );
}

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  if (req.mode === 'navigate') {
    e.respondWith(
      fetch(req)
        .then(res => {
          const copy = res.clone();
          caches.open(CACHE).then(c => c.put(req, copy)).catch(() => {});
          return res;
        })
        .catch(() => caches.match(req).then(r => r || caches.match('./index.html')))
    );
    return;
  }

  e.respondWith(
    caches.match(req).then(hit => hit || fetch(req).then(res => {
      if (res && res.ok && res.type === 'basic') {
        const copy = res.clone();
        caches.open(CACHE).then(c => c.put(req, copy)).catch(() => {});
      }
      return res;
    }))
  );
});
